samiha-rahman/SOEN341

woofer-theme/LICENSE
woofer-theme/footer.php
woofer-theme/functions.php
woofer-theme/header.php
woofer-theme/inc/custom-header.php
woofer-theme/inc/customizer.php
woofer-theme/inc/jetpack.php
woofer-theme/inc/template-functions.php
woofer-theme/inc/template-tags.php
woofer-theme/index.php
woofer-theme/js/customizer.js
woofer-theme/js/navigation.js
woofer-theme/js/skip-link-focus-fix.js
woofer-theme/languages/readme.txt
woofer-theme/languages/woofer.pot
woofer-theme/layouts/content-sidebar.css
woofer-theme/layouts/sidebar-content.css
woofer-theme/page.php
woofer-theme/style.css
woofer-theme/template-parts/content-none.php
woofer-theme/template-parts/content-page.php
woofer-theme/template-parts/content-search.php
woofer-theme/template-parts/content.php

The core of a WP theme from which we will build to provide the functionnality needed. This is a simple skeleton that provides the file structure and the most basic functions of a WP theme.

Theme boilerplate

---

woofer-theme/inc/template-functions.php

Editing template-functions.php to adhere to requirements in #15

---

woofer-theme/inc/template-functions.php
woofer-theme/register.php

Completion User Story #24 
Fixes #25 , #26 , #27

User Registration front-end

---

woofer-theme/inc/woof-post-type.php

Creating pull request for registration of post type

register woof post type, fixes #21

---

woofer-theme/inc/template-functions.php

Fixing redirect link in commit 90da85c7d8247a52250fe1ba28b37eeb6cef4054

Fixing redirect link

---

woofer-theme/inc/template-functions.php

This piece of code handles the displaying of the form and the handling of the data. On a successful login, the user is redirected to the homepage. On a unsuccessful login, the form simply wipes the information and the user needs to start over.
Resolving issue #29

Create custom login form

---

woofer-theme/login.php

This page template simply fetches the custom login form with the woof_custom_login() php function call.

Added page template for user login

---

woofer-theme/footer.php
woofer-theme/header.php
woofer-theme/inc/template-functions.php

Fixed template header and footer as well as an URL bug. Displayed menu nicely and added a "currently logged in as" entry to have a visual of the currently logged in user

Fixed header and footer

---

woofer-theme/profile.php

Link the template part to the profile.php template. Fixes #49

Linked the template part to profile template. Fixes #49

---

.travis.yml

Checks PHP syntax errors in all files. Will update later on to use PHP Code Sniffer against WordPress Coding Standards to perform more thorough tests.

Updating travis.yml file to run automated tests

---

woofer-theme/template-parts/show-woofs-on-follow.php

Part of the template to fix issue #66, however, still need a template for the following page to complete the task

Creating new page template to display posts by users followed, fixes #66

---

woofer-theme/following.php

posts can now be displayed by followed users, fixes issue #66

create core page template to display posts by followed users

---

woofer-theme/inc/template-functions.php

Handle AJAX call on server side. Fixes #71

Ajax call for server side Like

---

woofer-theme/js/like.js

Creating js file that handles ajax call for liking tweet

---

woofer-theme/inc/template-functions.php

Resolving bugs found by Travis-CI in failed builds

Resolving bug found in Job #118.4, fixes #87

---

woofer-theme/functions.php

Prepare php and javascript to communicate through AJAX by modifying my_enqueue() method. #69

Prepare php and javascript (LIke) Resolves issue #69

---

woofer-theme/template-parts/show-woofs-on-explore.php
woofer-theme/template-parts/show-woofs-on-follow.php
woofer-theme/template-parts/show-woofs-on-liked.php

Added the follow/unfollow and like/unlike buttons everywhere they needed to be in the frontend.

Fixes (finish) #73 #72 #64

---

woofer-theme/inc/template-functions.php
woofer-theme/js/like.js
woofer-theme/template-parts/good-boy-of-the-day.php
woofer-theme/template-parts/show-woofs-on-explore.php
woofer-theme/template-parts/show-woofs-on-follow.php
woofer-theme/template-parts/show-woofs-on-liked.php

Counter and redirection bug fixes

---

woofer-theme/inc/template-functions.php

Fixes redirection after registration

---

README.md

Adding landing page instructions

Updating set-up instructions

---

woofer-theme/register.php

Changing input type from "text" to "password"

Fixes bug #116
